/* 2026-09-22 从 09-21 21:22 的 renderer 构建 bundle(index-C_4vKAXg.js) 按 __name 切出的组件块。
   非原始 .vue：模板已编译成 render 函数、无类型标注，仅供重写参考。
   声明行: const _sfc_main$8 = /* @__PURE__ */ defineComponent(
*/
{
  __name: "AppIcon",
  props: {
    icon: {},
    size: { default: void 0 },
    color: { default: "currentColor" }
  },
  setup(__props) {
    const iconUrls = /* @__PURE__ */ Object.assign({
      "../assets/eagle-icons/icons/batch-save-select-all.svg": __vite_glob_0_0,
      "../assets/eagle-icons/icons/batch-save-select-invert.svg": __vite_glob_0_1,
      "../assets/eagle-icons/icons/context-menu/ic-add.svg": __vite_glob_0_2,
      "../assets/eagle-icons/icons/context-menu/ic-ai.svg": __vite_glob_0_3,
      "../assets/eagle-icons/icons/context-menu/ic-check-for-update.svg": __vite_glob_0_4,
      "../assets/eagle-icons/icons/context-menu/ic-clone.svg": __vite_glob_0_5,
      "../assets/eagle-icons/icons/context-menu/ic-context-menu-arrow-right.svg": __vite_glob_0_6,
      "../assets/eagle-icons/icons/context-menu/ic-context-menu-checkbox.svg": __vite_glob_0_7,
      "../assets/eagle-icons/icons/context-menu/ic-context-menu-more.svg": __vite_glob_0_8,
      "../assets/eagle-icons/icons/context-menu/ic-copy-duplicate.svg": __vite_glob_0_9,
      "../assets/eagle-icons/icons/context-menu/ic-copy-link.svg": __vite_glob_0_10,
      "../assets/eagle-icons/icons/context-menu/ic-developer.svg": __vite_glob_0_11,
      "../assets/eagle-icons/icons/context-menu/ic-eagle-logo.svg": __vite_glob_0_12,
      "../assets/eagle-icons/icons/context-menu/ic-emoji.svg": __vite_glob_0_13,
      "../assets/eagle-icons/icons/context-menu/ic-expand-all.svg": __vite_glob_0_14,
      "../assets/eagle-icons/icons/context-menu/ic-expand-same.svg": __vite_glob_0_15,
      "../assets/eagle-icons/icons/context-menu/ic-expand.svg": __vite_glob_0_16,
      "../assets/eagle-icons/icons/context-menu/ic-export-computer.svg": __vite_glob_0_17,
      "../assets/eagle-icons/icons/context-menu/ic-export-csv.svg": __vite_glob_0_18,
      "../assets/eagle-icons/icons/context-menu/ic-export-eaglepack.svg": __vite_glob_0_19,
      "../assets/eagle-icons/icons/context-menu/ic-export-format.svg": __vite_glob_0_20,
      "../assets/eagle-icons/icons/context-menu/ic-export.svg": __vite_glob_0_21,
      "../assets/eagle-icons/icons/context-menu/ic-favorite-add.svg": __vite_glob_0_22,
      "../assets/eagle-icons/icons/context-menu/ic-favorite-remove.svg": __vite_glob_0_23,
      "../assets/eagle-icons/icons/context-menu/ic-file-combine.svg": __vite_glob_0_24,
      "../assets/eagle-icons/icons/context-menu/ic-file-copy-ohters.svg": __vite_glob_0_25,
      "../assets/eagle-icons/icons/context-menu/ic-file-copy-path.svg": __vite_glob_0_26,
      "../assets/eagle-icons/icons/context-menu/ic-file-copy.svg": __vite_glob_0_27,
      "../assets/eagle-icons/icons/context-menu/ic-file-delete-permanently.svg": __vite_glob_0_28,
      "../assets/eagle-icons/icons/context-menu/ic-file-move-trash.svg": __vite_glob_0_29,
      "../assets/eagle-icons/icons/context-menu/ic-file-remove-folder.svg": __vite_glob_0_30,
      "../assets/eagle-icons/icons/context-menu/ic-file-transparent-grid.svg": __vite_glob_0_31,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-bpm.svg": __vite_glob_0_32,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-camera.svg": __vite_glob_0_33,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-color.svg": __vite_glob_0_34,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-comment.svg": __vite_glob_0_35,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-duration.svg": __vite_glob_0_36,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-ext.svg": __vite_glob_0_37,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-folder.svg": __vite_glob_0_38,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-font.svg": __vite_glob_0_39,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-image.svg": __vite_glob_0_40,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-import.svg": __vite_glob_0_41,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-modify.svg": __vite_glob_0_42,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-note.svg": __vite_glob_0_43,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-rating.svg": __vite_glob_0_44,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-resolution.svg": __vite_glob_0_45,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-semantic.svg": __vite_glob_0_46,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-shape.svg": __vite_glob_0_47,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-size.svg": __vite_glob_0_48,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-tag.svg": __vite_glob_0_49,
      "../assets/eagle-icons/icons/context-menu/ic-filter-item-url.svg": __vite_glob_0_50,
      "../assets/eagle-icons/icons/context-menu/ic-filter-pin.svg": __vite_glob_0_51,
      "../assets/eagle-icons/icons/context-menu/ic-filter-pinned.svg": __vite_glob_0_52,
      "../assets/eagle-icons/icons/context-menu/ic-find-duplicate.svg": __vite_glob_0_53,
      "../assets/eagle-icons/icons/context-menu/ic-folder-add-to.svg": __vite_glob_0_54,
      "../assets/eagle-icons/icons/context-menu/ic-folder-auto-tag.svg": __vite_glob_0_55,
      "../assets/eagle-icons/icons/context-menu/ic-folder-copy-link.svg": __vite_glob_0_56,
      "../assets/eagle-icons/icons/context-menu/ic-folder-last-used.svg": __vite_glob_0_57,
      "../assets/eagle-icons/icons/context-menu/ic-folder-move.svg": __vite_glob_0_58,
      "../assets/eagle-icons/icons/context-menu/ic-folder-new-folder.svg": __vite_glob_0_59,
      "../assets/eagle-icons/icons/context-menu/ic-folder-new-sub-folder.svg": __vite_glob_0_60,
      "../assets/eagle-icons/icons/context-menu/ic-folder-new-with-selection.svg": __vite_glob_0_61,
      "../assets/eagle-icons/icons/context-menu/ic-folder-remove.svg": __vite_glob_0_62,
      "../assets/eagle-icons/icons/context-menu/ic-folder-set-cover.svg": __vite_glob_0_63,
      "../assets/eagle-icons/icons/context-menu/ic-folder-show-sub-folder-content.svg": __vite_glob_0_64,
      "../assets/eagle-icons/icons/context-menu/ic-font-activate.svg": __vite_glob_0_65,
      "../assets/eagle-icons/icons/context-menu/ic-font-deactivate.svg": __vite_glob_0_66,
      "../assets/eagle-icons/icons/context-menu/ic-grayscale.svg": __vite_glob_0_67,
      "../assets/eagle-icons/icons/context-menu/ic-help.svg": __vite_glob_0_68,
      "../assets/eagle-icons/icons/context-menu/ic-icon-change.svg": __vite_glob_0_69,
      "../assets/eagle-icons/icons/context-menu/ic-icon-remove.svg": __vite_glob_0_70,
      "../assets/eagle-icons/icons/context-menu/ic-import-autoimport.svg": __vite_glob_0_71,
      "../assets/eagle-icons/icons/context-menu/ic-import-eaglepack.svg": __vite_glob_0_72,
      "../assets/eagle-icons/icons/context-menu/ic-import-links.svg": __vite_glob_0_73,
      "../assets/eagle-icons/icons/context-menu/ic-import-local.svg": __vite_glob_0_74,
      "../assets/eagle-icons/icons/context-menu/ic-inspector.svg": __vite_glob_0_75,
      "../assets/eagle-icons/icons/context-menu/ic-layout-grid.svg": __vite_glob_0_76,
      "../assets/eagle-icons/icons/context-menu/ic-layout-justified.svg": __vite_glob_0_77,
      "../assets/eagle-icons/icons/context-menu/ic-layout-list.svg": __vite_glob_0_78,
      "../assets/eagle-icons/icons/context-menu/ic-layout-pinterest.svg": __vite_glob_0_79,
      "../assets/eagle-icons/icons/context-menu/ic-library-add-to.svg": __vite_glob_0_80,
      "../assets/eagle-icons/icons/context-menu/ic-library-logo.svg": __vite_glob_0_81,
      "../assets/eagle-icons/icons/context-menu/ic-more-actions.svg": __vite_glob_0_82,
      "../assets/eagle-icons/icons/context-menu/ic-navigator.svg": __vite_glob_0_83,
      "../assets/eagle-icons/icons/context-menu/ic-open-default.svg": __vite_glob_0_84,
      "../assets/eagle-icons/icons/context-menu/ic-open-eagle.svg": __vite_glob_0_85,
      "../assets/eagle-icons/icons/context-menu/ic-open-explorer.svg": __vite_glob_0_86,
      "../assets/eagle-icons/icons/context-menu/ic-open-finder.svg": __vite_glob_0_87,
      "../assets/eagle-icons/icons/context-menu/ic-open-new-window.svg": __vite_glob_0_88,
      "../assets/eagle-icons/icons/context-menu/ic-open-other.svg": __vite_glob_0_89,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-btime.svg": __vite_glob_0_90,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-decrease.svg": __vite_glob_0_91,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-duration.svg": __vite_glob_0_92,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-ext.svg": __vite_glob_0_93,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-filesize.svg": __vite_glob_0_94,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-import.svg": __vite_glob_0_95,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-increase.svg": __vite_glob_0_96,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-mtime.svg": __vite_glob_0_97,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-name.svg": __vite_glob_0_98,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-random.svg": __vite_glob_0_99,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-rating.svg": __vite_glob_0_100,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-resolution.svg": __vite_glob_0_101,
      "../assets/eagle-icons/icons/context-menu/ic-order-by-tag.svg": __vite_glob_0_102,
      "../assets/eagle-icons/icons/context-menu/ic-order-by.svg": __vite_glob_0_103,
      "../assets/eagle-icons/icons/context-menu/ic-password.svg": __vite_glob_0_104,
      "../assets/eagle-icons/icons/context-menu/ic-pin.svg": __vite_glob_0_105,
      "../assets/eagle-icons/icons/context-menu/ic-plugin.svg": __vite_glob_0_106,
      "../assets/eagle-icons/icons/context-menu/ic-privacy.svg": __vite_glob_0_107,
      "../assets/eagle-icons/icons/context-menu/ic-refresh.svg": __vite_glob_0_108,
      "../assets/eagle-icons/icons/context-menu/ic-remove-from-list.svg": __vite_glob_0_109,
      "../assets/eagle-icons/icons/context-menu/ic-rename.svg": __vite_glob_0_110,
      "../assets/eagle-icons/icons/context-menu/ic-reset-range.svg": __vite_glob_0_111,
      "../assets/eagle-icons/icons/context-menu/ic-reverse-search.svg": __vite_glob_0_112,
      "../assets/eagle-icons/icons/context-menu/ic-roadmap.svg": __vite_glob_0_113,
      "../assets/eagle-icons/icons/context-menu/ic-saved-filter-apply.svg": __vite_glob_0_114,
      "../assets/eagle-icons/icons/context-menu/ic-saved-filter-create.svg": __vite_glob_0_115,
      "../assets/eagle-icons/icons/context-menu/ic-search-by-image.svg": __vite_glob_0_116,
      "../assets/eagle-icons/icons/context-menu/ic-search-scope-comment.svg": __vite_glob_0_117,
      "../assets/eagle-icons/icons/context-menu/ic-search-scope-ext.svg": __vite_glob_0_118,
      "../assets/eagle-icons/icons/context-menu/ic-search-scope-folder-desc.svg": __vite_glob_0_119,
      "../assets/eagle-icons/icons/context-menu/ic-search-scope-folder.svg": __vite_glob_0_120,
      "../assets/eagle-icons/icons/context-menu/ic-search-scope-link.svg": __vite_glob_0_121,
      "../assets/eagle-icons/icons/context-menu/ic-search-scope-name.svg": __vite_glob_0_122,
      "../assets/eagle-icons/icons/context-menu/ic-search-scope-note.svg": __vite_glob_0_123,
      "../assets/eagle-icons/icons/context-menu/ic-search-scope-tag.svg": __vite_glob_0_124,
      "../assets/eagle-icons/icons/context-menu/ic-set-thumbnail.svg": __vite_glob_0_125,
      "../assets/eagle-icons/icons/context-menu/ic-settings.svg": __vite_glob_0_126,
      "../assets/eagle-icons/icons/context-menu/ic-share.svg": __vite_glob_0_127,
      "../assets/eagle-icons/icons/context-menu/ic-shortcuts.svg": __vite_glob_0_128,
      "../assets/eagle-icons/icons/context-menu/ic-sidebar-all.svg": __vite_glob_0_129,
      "../assets/eagle-icons/icons/context-menu/ic-sidebar-community.svg": __vite_glob_0_130,
      "../assets/eagle-icons/icons/context-menu/ic-sidebar-random.svg": __vite_glob_0_131,
      "../assets/eagle-icons/icons/context-menu/ic-sidebar-recent.svg": __vite_glob_0_132,
      "../assets/eagle-icons/icons/context-menu/ic-sidebar-tag-manager.svg": __vite_glob_0_133,
      "../assets/eagle-icons/icons/context-menu/ic-sidebar-unfiled.svg": __vite_glob_0_134,
      "../assets/eagle-icons/icons/context-menu/ic-sidebar-untagged.svg": __vite_glob_0_135,
      "../assets/eagle-icons/icons/context-menu/ic-sidebar.svg": __vite_glob_0_136,
      "../assets/eagle-icons/icons/context-menu/ic-slideshow-off.svg": __vite_glob_0_137,
      "../assets/eagle-icons/icons/context-menu/ic-slideshow-on.svg": __vite_glob_0_138,
      "../assets/eagle-icons/icons/context-menu/ic-smart-folder-new-group.svg": __vite_glob_0_139,
      "../assets/eagle-icons/icons/context-menu/ic-smart-folder-new-sub.svg": __vite_glob_0_140,
      "../assets/eagle-icons/icons/context-menu/ic-smart-folder-new.svg": __vite_glob_0_141,
      "../assets/eagle-icons/icons/context-menu/ic-smart-folder-remove.svg": __vite_glob_0_142,
      "../assets/eagle-icons/icons/context-menu/ic-smart-folder-rule.svg": __vite_glob_0_143,
      "../assets/eagle-icons/icons/context-menu/ic-tag-add.svg": __vite_glob_0_144,
      "../assets/eagle-icons/icons/context-menu/ic-tag-aqua.svg": __vite_glob_0_145,
      "../assets/eagle-icons/icons/context-menu/ic-tag-blue.svg": __vite_glob_0_146,
      "../assets/eagle-icons/icons/context-menu/ic-tag-copy.svg": __vite_glob_0_147,
      "../assets/eagle-icons/icons/context-menu/ic-tag-delete.svg": __vite_glob_0_148,
      "../assets/eagle-icons/icons/context-menu/ic-tag-empty.svg": __vite_glob_0_149,
      "../assets/eagle-icons/icons/context-menu/ic-tag-filter.svg": __vite_glob_0_150,
      "../assets/eagle-icons/icons/context-menu/ic-tag-green.svg": __vite_glob_0_151,
      "../assets/eagle-icons/icons/context-menu/ic-tag-merge.svg": __vite_glob_0_152,
      "../assets/eagle-icons/icons/context-menu/ic-tag-move.svg": __vite_glob_0_153,
      "../assets/eagle-icons/icons/context-menu/ic-tag-normal.svg": __vite_glob_0_154,
      "../assets/eagle-icons/icons/context-menu/ic-tag-orange.svg": __vite_glob_0_155,
      "../assets/eagle-icons/icons/context-menu/ic-tag-paste.svg": __vite_glob_0_156,
      "../assets/eagle-icons/icons/context-menu/ic-tag-pink.svg": __vite_glob_0_157,
      "../assets/eagle-icons/icons/context-menu/ic-tag-purple.svg": __vite_glob_0_158,
      "../assets/eagle-icons/icons/context-menu/ic-tag-red.svg": __vite_glob_0_159,
      "../assets/eagle-icons/icons/context-menu/ic-tag-remove-group.svg": __vite_glob_0_160,
      "../assets/eagle-icons/icons/context-menu/ic-tag-remove.svg": __vite_glob_0_161,
      "../assets/eagle-icons/icons/context-menu/ic-tag-rename.svg": __vite_glob_0_162,
      "../assets/eagle-icons/icons/context-menu/ic-tag-star.svg": __vite_glob_0_163,
      "../assets/eagle-icons/icons/context-menu/ic-tag-undefined.svg": __vite_glob_0_164,
      "../assets/eagle-icons/icons/context-menu/ic-tag-unstar.svg": __vite_glob_0_165,
      "../assets/eagle-icons/icons/context-menu/ic-tag-yellow.svg": __vite_glob_0_166,
      "../assets/eagle-icons/icons/context-menu/ic-tips.svg": __vite_glob_0_167,
      "../assets/eagle-icons/icons/context-menu/ic-transparent-grid-black.svg": __vite_glob_0_168,
      "../assets/eagle-icons/icons/context-menu/ic-transparent-grid-gray.svg": __vite_glob_0_169,
      "../assets/eagle-icons/icons/context-menu/ic-transparent-grid-none.svg": __vite_glob_0_170,
      "../assets/eagle-icons/icons/context-menu/ic-transparent-grid-white.svg": __vite_glob_0_171,
      "../assets/eagle-icons/icons/context-menu/ic-transparent-grid.svg": __vite_glob_0_172,
      "../assets/eagle-icons/icons/context-menu/ic-trash-empty.svg": __vite_glob_0_173,
      "../assets/eagle-icons/icons/context-menu/ic-trash-restore.svg": __vite_glob_0_174,
      "../assets/eagle-icons/icons/context-menu/ic-twitter.svg": __vite_glob_0_175,
      "../assets/eagle-icons/icons/context-menu/ic-unpin.svg": __vite_glob_0_176,
      "../assets/eagle-icons/icons/context-menu/ic-video-copy-frame.svg": __vite_glob_0_177,
      "../assets/eagle-icons/icons/context-menu/ic-video-load-subtitle.svg": __vite_glob_0_178,
      "../assets/eagle-icons/icons/context-menu/ic-video-save-frame.svg": __vite_glob_0_179,
      "../assets/eagle-icons/icons/context-menu/ic-video-update-thumbnail.svg": __vite_glob_0_180,
      "../assets/eagle-icons/icons/context-menu/ic-webp-convert.svg": __vite_glob_0_181,
      "../assets/eagle-icons/icons/context-menu/templates/ic-artstation.png": __vite_glob_0_182,
      "../assets/eagle-icons/icons/context-menu/templates/ic-excel.png": __vite_glob_0_183,
      "../assets/eagle-icons/icons/context-menu/templates/ic-huaban.png": __vite_glob_0_184,
      "../assets/eagle-icons/icons/context-menu/templates/ic-illustration.png": __vite_glob_0_185,
      "../assets/eagle-icons/icons/context-menu/templates/ic-keynote.png": __vite_glob_0_186,
      "../assets/eagle-icons/icons/context-menu/templates/ic-mindnode.png": __vite_glob_0_187,
      "../assets/eagle-icons/icons/context-menu/templates/ic-numbers.png": __vite_glob_0_188,
      "../assets/eagle-icons/icons/context-menu/templates/ic-pages.png": __vite_glob_0_189,
      "../assets/eagle-icons/icons/context-menu/templates/ic-photoshop.png": __vite_glob_0_190,
      "../assets/eagle-icons/icons/context-menu/templates/ic-pinterest.png": __vite_glob_0_191,
      "../assets/eagle-icons/icons/context-menu/templates/ic-powerpoint.png": __vite_glob_0_192,
      "../assets/eagle-icons/icons/context-menu/templates/ic-sketch.png": __vite_glob_0_193,
      "../assets/eagle-icons/icons/context-menu/templates/ic-txt.png": __vite_glob_0_194,
      "../assets/eagle-icons/icons/context-menu/templates/ic-word.png": __vite_glob_0_195,
      "../assets/eagle-icons/icons/context-menu/templates/ic-xd.png": __vite_glob_0_196,
      "../assets/eagle-icons/icons/context-menu/templates/ic-xmind.png": __vite_glob_0_197,
      "../assets/eagle-icons/icons/filter/ic-logic-all.svg": __vite_glob_0_198,
      "../assets/eagle-icons/icons/filter/ic-logic-any.svg": __vite_glob_0_199,
      "../assets/eagle-icons/icons/filter/ic-logic-equal.svg": __vite_glob_0_200,
      "../assets/eagle-icons/icons/ic-action-create-step.svg": __vite_glob_0_201,
      "../assets/eagle-icons/icons/ic-action-create.svg": __vite_glob_0_202,
      "../assets/eagle-icons/icons/ic-action-rule-dropdown.svg": __vite_glob_0_203,
      "../assets/eagle-icons/icons/ic-action-rule-remove.svg": __vite_glob_0_204,
      "../assets/eagle-icons/icons/ic-app-menu.svg": __vite_glob_0_205,
      "../assets/eagle-icons/icons/ic-arrow-right.svg": __vite_glob_0_206,
      "../assets/eagle-icons/icons/ic-arrow-up.svg": __vite_glob_0_207,
      "../assets/eagle-icons/icons/ic-check.svg": __vite_glob_0_208,
      "../assets/eagle-icons/icons/ic-condition-add.svg": __vite_glob_0_209,
      "../assets/eagle-icons/icons/ic-condition-remove.svg": __vite_glob_0_210,
      "../assets/eagle-icons/icons/ic-drag-help.svg": __vite_glob_0_211,
      "../assets/eagle-icons/icons/ic-duplicate-remove-group.svg": __vite_glob_0_212,
      "../assets/eagle-icons/icons/ic-filter-add.svg": __vite_glob_0_213,
      "../assets/eagle-icons/icons/ic-filter-clear-btn.png": __vite_glob_0_214,
      "../assets/eagle-icons/icons/ic-filter-lock.svg": __vite_glob_0_215,
      "../assets/eagle-icons/icons/ic-filter-reset.svg": __vite_glob_0_216,
      "../assets/eagle-icons/icons/ic-filter-saved.svg": __vite_glob_0_217,
      "../assets/eagle-icons/icons/ic-filter.svg": __vite_glob_0_218,
      "../assets/eagle-icons/icons/ic-folder-select-all.svg": __vite_glob_0_219,
      "../assets/eagle-icons/icons/ic-folder-select-create.svg": __vite_glob_0_220,
      "../assets/eagle-icons/icons/ic-folder-select-recent.svg": __vite_glob_0_221,
      "../assets/eagle-icons/icons/ic-folder-select-selected.svg": __vite_glob_0_222,
      "../assets/eagle-icons/icons/ic-help-btn.svg": __vite_glob_0_223,
      "../assets/eagle-icons/icons/ic-hover-zoom.svg": __vite_glob_0_224,
      "../assets/eagle-icons/icons/ic-inline-exit-btn.svg": __vite_glob_0_225,
      "../assets/eagle-icons/icons/ic-inline-mode-split.svg": __vite_glob_0_226,
      "../assets/eagle-icons/icons/ic-inline-next-btn.svg": __vite_glob_0_227,
      "../assets/eagle-icons/icons/ic-inline-prev-btn.svg": __vite_glob_0_228,
      "../assets/eagle-icons/icons/ic-inspector-add-label.svg": __vite_glob_0_229,
      "../assets/eagle-icons/icons/ic-inspector-comment-edit.svg": __vite_glob_0_230,
      "../assets/eagle-icons/icons/ic-inspector-comment-remove.svg": __vite_glob_0_231,
      "../assets/eagle-icons/icons/ic-inspector-expand.svg": __vite_glob_0_232,
      "../assets/eagle-icons/icons/ic-inspector-export.svg": __vite_glob_0_233,
      "../assets/eagle-icons/icons/ic-inspector-open-link.svg": __vite_glob_0_234,
      "../assets/eagle-icons/icons/ic-inspector-remove-label.svg": __vite_glob_0_235,
      "../assets/eagle-icons/icons/ic-inspector-warning.png": __vite_glob_0_236,
      "../assets/eagle-icons/icons/ic-layout-grid.svg": __vite_glob_0_237,
      "../assets/eagle-icons/icons/ic-layout-justified.svg": __vite_glob_0_238,
      "../assets/eagle-icons/icons/ic-layout-list.svg": __vite_glob_0_239,
      "../assets/eagle-icons/icons/ic-layout-pinterest.svg": __vite_glob_0_240,
      "../assets/eagle-icons/icons/ic-library-opened.svg": __vite_glob_0_241,
      "../assets/eagle-icons/icons/ic-library-panel-create.svg": __vite_glob_0_242,
      "../assets/eagle-icons/icons/ic-library-panel-load.svg": __vite_glob_0_243,
      "../assets/eagle-icons/icons/ic-library-panel-merge.svg": __vite_glob_0_244,
      "../assets/eagle-icons/icons/ic-library-panel-reload.svg": __vite_glob_0_245,
      "../assets/eagle-icons/icons/ic-list-arrow-down.svg": __vite_glob_0_246,
      "../assets/eagle-icons/icons/ic-list-remove.svg": __vite_glob_0_247,
      "../assets/eagle-icons/icons/ic-list-sub-folder-lock.svg": __vite_glob_0_248,
      "../assets/eagle-icons/icons/ic-lock-folder.svg": __vite_glob_0_249,
      "../assets/eagle-icons/icons/ic-manage-device-edit.svg": __vite_glob_0_250,
      "../assets/eagle-icons/icons/ic-manage-device-remove.svg": __vite_glob_0_251,
      "../assets/eagle-icons/icons/ic-modal-back.svg": __vite_glob_0_252,
      "../assets/eagle-icons/icons/ic-modal-close.svg": __vite_glob_0_253,
      "../assets/eagle-icons/icons/ic-modal-status-create.svg": __vite_glob_0_254,
      "../assets/eagle-icons/icons/ic-modal-status-error.svg": __vite_glob_0_255,
      "../assets/eagle-icons/icons/ic-modal-status-filter.svg": __vite_glob_0_256,
      "../assets/eagle-icons/icons/ic-modal-status-info.svg": __vite_glob_0_257,
      "../assets/eagle-icons/icons/ic-modal-status-library.svg": __vite_glob_0_258,
      "../assets/eagle-icons/icons/ic-modal-status-links.svg": __vite_glob_0_259,
      "../assets/eagle-icons/icons/ic-modal-status-success.svg": __vite_glob_0_260,
      "../assets/eagle-icons/icons/ic-modal-status-warning.svg": __vite_glob_0_261,
      "../assets/eagle-icons/icons/ic-more.svg": __vite_glob_0_262,
      "../assets/eagle-icons/icons/ic-panel-item-expand.svg": __vite_glob_0_263,
      "../assets/eagle-icons/icons/ic-plugin-center-develop.svg": __vite_glob_0_264,
      "../assets/eagle-icons/icons/ic-plugin-developer.svg": __vite_glob_0_265,
      "../assets/eagle-icons/icons/ic-plugin-install-modal-created.svg": __vite_glob_0_266,
      "../assets/eagle-icons/icons/ic-plugin-install-modal-download.svg": __vite_glob_0_267,
      "../assets/eagle-icons/icons/ic-plugin-install-modal-uninstall.svg": __vite_glob_0_268,
      "../assets/eagle-icons/icons/ic-plugin-install-modal-update.svg": __vite_glob_0_269,
      "../assets/eagle-icons/icons/ic-plugin-install.svg": __vite_glob_0_270,
      "../assets/eagle-icons/icons/ic-plugin-list-download.svg": __vite_glob_0_271,
      "../assets/eagle-icons/icons/ic-plugin-list-installed.svg": __vite_glob_0_272,
      "../assets/eagle-icons/icons/ic-plugin-list-needupdate.svg": __vite_glob_0_273,
      "../assets/eagle-icons/icons/ic-plugin-list-uninstall.svg": __vite_glob_0_274,
      "../assets/eagle-icons/icons/ic-plugin-list-update.svg": __vite_glob_0_275,
      "../assets/eagle-icons/icons/ic-plugin-local.svg": __vite_glob_0_276,
      "../assets/eagle-icons/icons/ic-plugin-panel-back.svg": __vite_glob_0_277,
      "../assets/eagle-icons/icons/ic-plugin-prop-collect.svg": __vite_glob_0_278,
      "../assets/eagle-icons/icons/ic-plugin-prop-developer.svg": __vite_glob_0_279,
      "../assets/eagle-icons/icons/ic-plugin-prop-download.svg": __vite_glob_0_280,
      "../assets/eagle-icons/icons/ic-plugin-prop-site.svg": __vite_glob_0_281,
      "../assets/eagle-icons/icons/ic-plugin-prop-support.svg": __vite_glob_0_282,
      "../assets/eagle-icons/icons/ic-plugin-prop-version.svg": __vite_glob_0_283,
      "../assets/eagle-icons/icons/ic-plugin-prop-view.svg": __vite_glob_0_284,
      "../assets/eagle-icons/icons/ic-plugin-type-ai-tools.svg": __vite_glob_0_285,
      "../assets/eagle-icons/icons/ic-plugin-type-all.svg": __vite_glob_0_286,
      "../assets/eagle-icons/icons/ic-plugin-type-converter.svg": __vite_glob_0_287,
      "../assets/eagle-icons/icons/ic-plugin-type-downloader.svg": __vite_glob_0_288,
      "../assets/eagle-icons/icons/ic-plugin-type-format.svg": __vite_glob_0_289,
      "../assets/eagle-icons/icons/ic-plugin-type-image.svg": __vite_glob_0_290,
      "../assets/eagle-icons/icons/ic-plugin-type-inspector.svg": __vite_glob_0_291,
      "../assets/eagle-icons/icons/ic-plugin-type-others.svg": __vite_glob_0_292,
      "../assets/eagle-icons/icons/ic-plugin-type-productivity.svg": __vite_glob_0_293,
      "../assets/eagle-icons/icons/ic-plugin-type-update.svg": __vite_glob_0_294,
      "../assets/eagle-icons/icons/ic-plugin-type-video.svg": __vite_glob_0_295,
      "../assets/eagle-icons/icons/ic-prop-createdAt.svg": __vite_glob_0_296,
      "../assets/eagle-icons/icons/ic-prop-dimension.svg": __vite_glob_0_297,
      "../assets/eagle-icons/icons/ic-prop-duration.svg": __vite_glob_0_298,
      "../assets/eagle-icons/icons/ic-prop-ext.svg": __vite_glob_0_299,
      "../assets/eagle-icons/icons/ic-prop-fileSize.svg": __vite_glob_0_300,
      "../assets/eagle-icons/icons/ic-prop-importAt.svg": __vite_glob_0_301,
      "../assets/eagle-icons/icons/ic-prop-modifiedAt.svg": __vite_glob_0_302,
      "../assets/eagle-icons/icons/ic-prop-name.svg": __vite_glob_0_303,
      "../assets/eagle-icons/icons/ic-prop-rating.svg": __vite_glob_0_304,
      "../assets/eagle-icons/icons/ic-prop-shuffle.svg": __vite_glob_0_305,
      "../assets/eagle-icons/icons/ic-prop-tag.svg": __vite_glob_0_306,
      "../assets/eagle-icons/icons/ic-rainbow-btn.png": __vite_glob_0_307,
      "../assets/eagle-icons/icons/ic-refresh.svg": __vite_glob_0_308,
      "../assets/eagle-icons/icons/ic-remind-later.svg": __vite_glob_0_309,
      "../assets/eagle-icons/icons/ic-scroll-top.svg": __vite_glob_0_310,
      "../assets/eagle-icons/icons/ic-search-by-image-empty.svg": __vite_glob_0_311,
      "../assets/eagle-icons/icons/ic-search-by-image.svg": __vite_glob_0_312,
      "../assets/eagle-icons/icons/ic-search-history-remove.svg": __vite_glob_0_313,
      "../assets/eagle-icons/icons/ic-separator.svg": __vite_glob_0_314,
      "../assets/eagle-icons/icons/ic-sidebar-add.svg": __vite_glob_0_315,
      "../assets/eagle-icons/icons/ic-slow-warning.svg": __vite_glob_0_316,
      "../assets/eagle-icons/icons/ic-sortDecreace.svg": __vite_glob_0_317,
      "../assets/eagle-icons/icons/ic-sortIncreace.svg": __vite_glob_0_318,
      "../assets/eagle-icons/icons/ic-status-pause.svg": __vite_glob_0_319,
      "../assets/eagle-icons/icons/ic-tag-manager-all.svg": __vite_glob_0_320,
      "../assets/eagle-icons/icons/ic-tag-manager-layout-grid.svg": __vite_glob_0_321,
      "../assets/eagle-icons/icons/ic-tag-manager-layout-list.svg": __vite_glob_0_322,
      "../assets/eagle-icons/icons/ic-tag-manager-sort.svg": __vite_glob_0_323,
      "../assets/eagle-icons/icons/ic-tag-manager-starred.svg": __vite_glob_0_324,
      "../assets/eagle-icons/icons/ic-tag-manager-unfiled.svg": __vite_glob_0_325,
      "../assets/eagle-icons/icons/ic-tag-remove.svg": __vite_glob_0_326,
      "../assets/eagle-icons/icons/ic-tag-select-create.svg": __vite_glob_0_327,
      "../assets/eagle-icons/icons/ic-tag-settings.svg": __vite_glob_0_328,
      "../assets/eagle-icons/icons/ic-toast-error.svg": __vite_glob_0_329,
      "../assets/eagle-icons/icons/ic-toast-success.svg": __vite_glob_0_330,
      "../assets/eagle-icons/icons/ic-toast-warning.svg": __vite_glob_0_331,
      "../assets/eagle-icons/icons/ic-toolbar-action.svg": __vite_glob_0_332,
      "../assets/eagle-icons/icons/ic-toolbar-arrow-down.svg": __vite_glob_0_333,
      "../assets/eagle-icons/icons/ic-toolbar-close.svg": __vite_glob_0_334,
      "../assets/eagle-icons/icons/ic-toolbar-comment.svg": __vite_glob_0_335,
      "../assets/eagle-icons/icons/ic-toolbar-crop.svg": __vite_glob_0_336,
      "../assets/eagle-icons/icons/ic-toolbar-exit.svg": __vite_glob_0_337,
      "../assets/eagle-icons/icons/ic-toolbar-filter.svg": __vite_glob_0_338,
      "../assets/eagle-icons/icons/ic-toolbar-flip.svg": __vite_glob_0_339,
      "../assets/eagle-icons/icons/ic-toolbar-gif-frames.svg": __vite_glob_0_340,
      "../assets/eagle-icons/icons/ic-toolbar-layout.svg": __vite_glob_0_341,
      "../assets/eagle-icons/icons/ic-toolbar-next.svg": __vite_glob_0_342,
      "../assets/eagle-icons/icons/ic-toolbar-open-default.svg": __vite_glob_0_343,
      "../assets/eagle-icons/icons/ic-toolbar-pin.svg": __vite_glob_0_344,
      "../assets/eagle-icons/icons/ic-toolbar-plugin.svg": __vite_glob_0_345,
      "../assets/eagle-icons/icons/ic-toolbar-prev.svg": __vite_glob_0_346,
      "../assets/eagle-icons/icons/ic-toolbar-rotate.svg": __vite_glob_0_347,
      "../assets/eagle-icons/icons/ic-toolbar-unpin.svg": __vite_glob_0_348,
      "../assets/eagle-icons/icons/ic-toolbar-zoom-actual.svg": __vite_glob_0_349,
      "../assets/eagle-icons/icons/ic-toolbar-zoom-fit.svg": __vite_glob_0_350,
      "../assets/eagle-icons/icons/ic-toolbar-zoom-in.svg": __vite_glob_0_351,
      "../assets/eagle-icons/icons/ic-toolbar-zoom-out.svg": __vite_glob_0_352,
      "../assets/eagle-icons/icons/ic-touchid.svg": __vite_glob_0_353,
      "../assets/eagle-icons/icons/ic-welcome-extenstion-download.svg": __vite_glob_0_354,
      "../assets/eagle-icons/icons/ic-welcome-library-create.svg": __vite_glob_0_355,
      "../assets/eagle-icons/icons/ic-welcome-library-import.svg": __vite_glob_0_356,
      "../assets/eagle-icons/icons/ic-welcome-library-missing-icon.png": __vite_glob_0_357,
      "../assets/eagle-icons/icons/ic-window-pin.svg": __vite_glob_0_358,
      "../assets/eagle-icons/icons/ic-window-unpin.svg": __vite_glob_0_359,
      "../assets/eagle-icons/icons/ic-windows-close.svg": __vite_glob_0_360,
      "../assets/eagle-icons/icons/ic-windows-fullscreen.svg": __vite_glob_0_361,
      "../assets/eagle-icons/icons/ic-windows-hide.svg": __vite_glob_0_362,
      "../assets/eagle-icons/icons/ic-windows-restore.svg": __vite_glob_0_363,
      "../assets/eagle-icons/icons/ic_add.svg": __vite_glob_0_364,
      "../assets/eagle-icons/icons/ic_notification.svg": __vite_glob_0_365,
      "../assets/eagle-icons/icons/ic_refresh.svg": __vite_glob_0_366,
      "../assets/eagle-icons/icons/ic_search.svg": __vite_glob_0_367,
      "../assets/eagle-icons/icons/ic_search_close.svg": __vite_glob_0_368,
      "../assets/eagle-icons/icons/ic_switch.svg": __vite_glob_0_369,
      "../assets/eagle-icons/icons/ic_toggle-sidebar.svg": __vite_glob_0_370,
      "../assets/eagle-icons/icons/ic_unfold-more.svg": __vite_glob_0_371,
      "../assets/eagle-icons/icons/player/ic-menu.check.svg": __vite_glob_0_372,
      "../assets/eagle-icons/icons/player/ic-toolbar-backward.svg": __vite_glob_0_373,
      "../assets/eagle-icons/icons/player/ic-toolbar-forward.svg": __vite_glob_0_374,
      "../assets/eagle-icons/icons/player/ic-toolbar-fullscreen.svg": __vite_glob_0_375,
      "../assets/eagle-icons/icons/player/ic-toolbar-loop.svg": __vite_glob_0_376,
      "../assets/eagle-icons/icons/player/ic-toolbar-more.svg": __vite_glob_0_377,
      "../assets/eagle-icons/icons/player/ic-toolbar-note.svg": __vite_glob_0_378,
      "../assets/eagle-icons/icons/player/ic-toolbar-pause.svg": __vite_glob_0_379,
      "../assets/eagle-icons/icons/player/ic-toolbar-play.svg": __vite_glob_0_380,
      "../assets/eagle-icons/icons/player/ic-toolbar-volume-0.svg": __vite_glob_0_381,
      "../assets/eagle-icons/icons/player/ic-toolbar-volume-1.svg": __vite_glob_0_382,
      "../assets/eagle-icons/icons/player/ic-toolbar-volume-2.svg": __vite_glob_0_383,
      "../assets/eagle-icons/icons/player/ic-toolbar-volume-3.svg": __vite_glob_0_384,
      "../assets/eagle-icons/icons/preferences/ic-copy.svg": __vite_glob_0_385,
      "../assets/eagle-icons/icons/preferences/ic-edit.svg": __vite_glob_0_386,
      "../assets/eagle-icons/icons/preferences/ic-folder.svg": __vite_glob_0_387,
      "../assets/eagle-icons/icons/preferences/ic-hover-tip.svg": __vite_glob_0_388,
      "../assets/eagle-icons/icons/preferences/ic-link.svg": __vite_glob_0_389,
      "../assets/eagle-icons/icons/preferences/ic-lock.svg": __vite_glob_0_390,
      "../assets/eagle-icons/icons/preferences/ic-next.svg": __vite_glob_0_391,
      "../assets/eagle-icons/icons/preferences/ic-touchid.svg": __vite_glob_0_392,
      "../assets/eagle-icons/icons/preferences/ic-watch-folder.svg": __vite_glob_0_393,
      "../assets/eagle-icons/icons/progress/ic-progress-download.png": __vite_glob_0_394,
      "../assets/eagle-icons/icons/webview/ic-webview-backward.svg": __vite_glob_0_395,
      "../assets/eagle-icons/icons/webview/ic-webview-copy-url.svg": __vite_glob_0_396,
      "../assets/eagle-icons/icons/webview/ic-webview-forward.svg": __vite_glob_0_397,
      "../assets/eagle-icons/icons/webview/ic-webview-open-external.svg": __vite_glob_0_398,
      "../assets/eagle-icons/icons/webview/ic-webview-refresh.svg": __vite_glob_0_399
    });
    const maskUrls = /* @__PURE__ */ Object.assign({
      "../assets/eagle-icons/masks/ic_2d.png": __vite_glob_1_0,
      "../assets/eagle-icons/masks/ic_3d.png": __vite_glob_1_1,
      "../assets/eagle-icons/masks/ic_airplan.png": __vite_glob_1_2,
      "../assets/eagle-icons/masks/ic_all.png": __vite_glob_1_3,
      "../assets/eagle-icons/masks/ic_alltags.png": __vite_glob_1_4,
      "../assets/eagle-icons/masks/ic_angel.png": __vite_glob_1_5,
      "../assets/eagle-icons/masks/ic_animation.png": __vite_glob_1_6,
      "../assets/eagle-icons/masks/ic_aperture.png": __vite_glob_1_7,
      "../assets/eagle-icons/masks/ic_armor.png": __vite_glob_1_8,
      "../assets/eagle-icons/masks/ic_attachment.png": __vite_glob_1_9,
      "../assets/eagle-icons/masks/ic_award.png": __vite_glob_1_10,
      "../assets/eagle-icons/masks/ic_award2.png": __vite_glob_1_11,
      "../assets/eagle-icons/masks/ic_award3.png": __vite_glob_1_12,
      "../assets/eagle-icons/masks/ic_baby.png": __vite_glob_1_13,
      "../assets/eagle-icons/masks/ic_bachelor-cap.png": __vite_glob_1_14,
      "../assets/eagle-icons/masks/ic_bar-chart.png": __vite_glob_1_15,
      "../assets/eagle-icons/masks/ic_bathtub.png": __vite_glob_1_16,
      "../assets/eagle-icons/masks/ic_bear.png": __vite_glob_1_17,
      "../assets/eagle-icons/masks/ic_bed.png": __vite_glob_1_18,
      "../assets/eagle-icons/masks/ic_book.png": __vite_glob_1_19,
      "../assets/eagle-icons/masks/ic_book2.png": __vite_glob_1_20,
      "../assets/eagle-icons/masks/ic_bookshelf.png": __vite_glob_1_21,
      "../assets/eagle-icons/masks/ic_box.png": __vite_glob_1_22,
      "../assets/eagle-icons/masks/ic_brain.png": __vite_glob_1_23,
      "../assets/eagle-icons/masks/ic_briefcase.png": __vite_glob_1_24,
      "../assets/eagle-icons/masks/ic_business-card.png": __vite_glob_1_25,
      "../assets/eagle-icons/masks/ic_cabinet.png": __vite_glob_1_26,
      "../assets/eagle-icons/masks/ic_calendar-month.png": __vite_glob_1_27,
      "../assets/eagle-icons/masks/ic_calendar-week.png": __vite_glob_1_28,
      "../assets/eagle-icons/masks/ic_camera.png": __vite_glob_1_29,
      "../assets/eagle-icons/masks/ic_car.png": __vite_glob_1_30,
      "../assets/eagle-icons/masks/ic_cart.png": __vite_glob_1_31,
      "../assets/eagle-icons/masks/ic_cat.png": __vite_glob_1_32,
      "../assets/eagle-icons/masks/ic_chrome.png": __vite_glob_1_33,
      "../assets/eagle-icons/masks/ic_clock.png": __vite_glob_1_34,
      "../assets/eagle-icons/masks/ic_cloud.png": __vite_glob_1_35,
      "../assets/eagle-icons/masks/ic_coffee.png": __vite_glob_1_36,
      "../assets/eagle-icons/masks/ic_cog.png": __vite_glob_1_37,
      "../assets/eagle-icons/masks/ic_coin1.png": __vite_glob_1_38,
      "../assets/eagle-icons/masks/ic_coin2.png": __vite_glob_1_39,
      "../assets/eagle-icons/masks/ic_coin3.png": __vite_glob_1_40,
      "../assets/eagle-icons/masks/ic_coin4.png": __vite_glob_1_41,
      "../assets/eagle-icons/masks/ic_community.png": __vite_glob_1_42,
      "../assets/eagle-icons/masks/ic_cones.png": __vite_glob_1_43,
      "../assets/eagle-icons/masks/ic_contrast.png": __vite_glob_1_44,
      "../assets/eagle-icons/masks/ic_cpu.png": __vite_glob_1_45,
      "../assets/eagle-icons/masks/ic_crown.png": __vite_glob_1_46,
      "../assets/eagle-icons/masks/ic_demon.png": __vite_glob_1_47,
      "../assets/eagle-icons/masks/ic_desktop.png": __vite_glob_1_48,
      "../assets/eagle-icons/masks/ic_die.png": __vite_glob_1_49,
      "../assets/eagle-icons/masks/ic_dog.png": __vite_glob_1_50,
      "../assets/eagle-icons/masks/ic_door.png": __vite_glob_1_51,
      "../assets/eagle-icons/masks/ic_download.png": __vite_glob_1_52,
      "../assets/eagle-icons/masks/ic_dribbble.png": __vite_glob_1_53,
      "../assets/eagle-icons/masks/ic_earth.png": __vite_glob_1_54,
      "../assets/eagle-icons/masks/ic_email.png": __vite_glob_1_55,
      "../assets/eagle-icons/masks/ic_excalmation.png": __vite_glob_1_56,
      "../assets/eagle-icons/masks/ic_eye.png": __vite_glob_1_57,
      "../assets/eagle-icons/masks/ic_facebook.png": __vite_glob_1_58,
      "../assets/eagle-icons/masks/ic_film.png": __vite_glob_1_59,
      "../assets/eagle-icons/masks/ic_film2.png": __vite_glob_1_60,
      "../assets/eagle-icons/masks/ic_film3.png": __vite_glob_1_61,
      "../assets/eagle-icons/masks/ic_flag.png": __vite_glob_1_62,
      "../assets/eagle-icons/masks/ic_folder-close.png": __vite_glob_1_63,
      "../assets/eagle-icons/masks/ic_folder-open.png": __vite_glob_1_64,
      "../assets/eagle-icons/masks/ic_font-handwritten.png": __vite_glob_1_65,
      "../assets/eagle-icons/masks/ic_font-sans-serif.png": __vite_glob_1_66,
      "../assets/eagle-icons/masks/ic_font-sans.png": __vite_glob_1_67,
      "../assets/eagle-icons/masks/ic_free.png": __vite_glob_1_68,
      "../assets/eagle-icons/masks/ic_frown.png": __vite_glob_1_69,
      "../assets/eagle-icons/masks/ic_game.png": __vite_glob_1_70,
      "../assets/eagle-icons/masks/ic_gift.png": __vite_glob_1_71,
      "../assets/eagle-icons/masks/ic_graph.png": __vite_glob_1_72,
      "../assets/eagle-icons/masks/ic_graph2.png": __vite_glob_1_73,
      "../assets/eagle-icons/masks/ic_grid.png": __vite_glob_1_74,
      "../assets/eagle-icons/masks/ic_group.png": __vite_glob_1_75,
      "../assets/eagle-icons/masks/ic_hand.png": __vite_glob_1_76,
      "../assets/eagle-icons/masks/ic_helmet.png": __vite_glob_1_77,
      "../assets/eagle-icons/masks/ic_home.png": __vite_glob_1_78,
      "../assets/eagle-icons/masks/ic_hot.png": __vite_glob_1_79,
      "../assets/eagle-icons/masks/ic_house.png": __vite_glob_1_80,
      "../assets/eagle-icons/masks/ic_inspiration.png": __vite_glob_1_81,
      "../assets/eagle-icons/masks/ic_instagram.png": __vite_glob_1_82,
      "../assets/eagle-icons/masks/ic_keynote.png": __vite_glob_1_83,
      "../assets/eagle-icons/masks/ic_kid.png": __vite_glob_1_84,
      "../assets/eagle-icons/masks/ic_layer.png": __vite_glob_1_85,
      "../assets/eagle-icons/masks/ic_library.png": __vite_glob_1_86,
      "../assets/eagle-icons/masks/ic_life-buoy.png": __vite_glob_1_87,
      "../assets/eagle-icons/masks/ic_lightbulb.png": __vite_glob_1_88,
      "../assets/eagle-icons/masks/ic_like.png": __vite_glob_1_89,
      "../assets/eagle-icons/masks/ic_line-chart.png": __vite_glob_1_90,
      "../assets/eagle-icons/masks/ic_man.png": __vite_glob_1_91,
      "../assets/eagle-icons/masks/ic_map.png": __vite_glob_1_92,
      "../assets/eagle-icons/masks/ic_medical.png": __vite_glob_1_93,
      "../assets/eagle-icons/masks/ic_meh.png": __vite_glob_1_94,
      "../assets/eagle-icons/masks/ic_moon.png": __vite_glob_1_95,
      "../assets/eagle-icons/masks/ic_motor.png": __vite_glob_1_96,
      "../assets/eagle-icons/masks/ic_mountain.png": __vite_glob_1_97,
      "../assets/eagle-icons/masks/ic_music.png": __vite_glob_1_98,
      "../assets/eagle-icons/masks/ic_number0.png": __vite_glob_1_99,
      "../assets/eagle-icons/masks/ic_number1.png": __vite_glob_1_100,
      "../assets/eagle-icons/masks/ic_number10.png": __vite_glob_1_101,
      "../assets/eagle-icons/masks/ic_number11.png": __vite_glob_1_102,
      "../assets/eagle-icons/masks/ic_number12.png": __vite_glob_1_103,
      "../assets/eagle-icons/masks/ic_number13.png": __vite_glob_1_104,
      "../assets/eagle-icons/masks/ic_number14.png": __vite_glob_1_105,
      "../assets/eagle-icons/masks/ic_number15.png": __vite_glob_1_106,
      "../assets/eagle-icons/masks/ic_number16.png": __vite_glob_1_107,
      "../assets/eagle-icons/masks/ic_number17.png": __vite_glob_1_108,
      "../assets/eagle-icons/masks/ic_number18.png": __vite_glob_1_109,
      "../assets/eagle-icons/masks/ic_number19.png": __vite_glob_1_110,
      "../assets/eagle-icons/masks/ic_number2.png": __vite_glob_1_111,
      "../assets/eagle-icons/masks/ic_number20.png": __vite_glob_1_112,
      "../assets/eagle-icons/masks/ic_number3.png": __vite_glob_1_113,
      "../assets/eagle-icons/masks/ic_number4.png": __vite_glob_1_114,
      "../assets/eagle-icons/masks/ic_number5.png": __vite_glob_1_115,
      "../assets/eagle-icons/masks/ic_number6.png": __vite_glob_1_116,
      "../assets/eagle-icons/masks/ic_number7.png": __vite_glob_1_117,
      "../assets/eagle-icons/masks/ic_number8.png": __vite_glob_1_118,
      "../assets/eagle-icons/masks/ic_number9.png": __vite_glob_1_119,
      "../assets/eagle-icons/masks/ic_paid.png": __vite_glob_1_120,
      "../assets/eagle-icons/masks/ic_palette.png": __vite_glob_1_121,
      "../assets/eagle-icons/masks/ic_phone.png": __vite_glob_1_122,
      "../assets/eagle-icons/masks/ic_photo.png": __vite_glob_1_123,
      "../assets/eagle-icons/masks/ic_photos.png": __vite_glob_1_124,
      "../assets/eagle-icons/masks/ic_pie.png": __vite_glob_1_125,
      "../assets/eagle-icons/masks/ic_pin-check.png": __vite_glob_1_126,
      "../assets/eagle-icons/masks/ic_pin.png": __vite_glob_1_127,
      "../assets/eagle-icons/masks/ic_question.png": __vite_glob_1_128,
      "../assets/eagle-icons/masks/ic_random.png": __vite_glob_1_129,
      "../assets/eagle-icons/masks/ic_recycle.png": __vite_glob_1_130,
      "../assets/eagle-icons/masks/ic_road.png": __vite_glob_1_131,
      "../assets/eagle-icons/masks/ic_rocket.png": __vite_glob_1_132,
      "../assets/eagle-icons/masks/ic_rophy.png": __vite_glob_1_133,
      "../assets/eagle-icons/masks/ic_safari.png": __vite_glob_1_134,
      "../assets/eagle-icons/masks/ic_scissors.png": __vite_glob_1_135,
      "../assets/eagle-icons/masks/ic_search.png": __vite_glob_1_136,
      "../assets/eagle-icons/masks/ic_shield.png": __vite_glob_1_137,
      "../assets/eagle-icons/masks/ic_ship.png": __vite_glob_1_138,
      "../assets/eagle-icons/masks/ic_shortcuts.png": __vite_glob_1_139,
      "../assets/eagle-icons/masks/ic_smart-folder.png": __vite_glob_1_140,
      "../assets/eagle-icons/masks/ic_smile.png": __vite_glob_1_141,
      "../assets/eagle-icons/masks/ic_sofa.png": __vite_glob_1_142,
      "../assets/eagle-icons/masks/ic_spectrogram.png": __vite_glob_1_143,
      "../assets/eagle-icons/masks/ic_star.png": __vite_glob_1_144,
      "../assets/eagle-icons/masks/ic_store.png": __vite_glob_1_145,
      "../assets/eagle-icons/masks/ic_sun.png": __vite_glob_1_146,
      "../assets/eagle-icons/masks/ic_tablet.png": __vite_glob_1_147,
      "../assets/eagle-icons/masks/ic_tableware.png": __vite_glob_1_148,
      "../assets/eagle-icons/masks/ic_tagAll.png": __vite_glob_1_149,
      "../assets/eagle-icons/masks/ic_tagStarred.png": __vite_glob_1_150,
      "../assets/eagle-icons/masks/ic_tagUncategorized.png": __vite_glob_1_151,
      "../assets/eagle-icons/masks/ic_texture.png": __vite_glob_1_152,
      "../assets/eagle-icons/masks/ic_thumb-down.png": __vite_glob_1_153,
      "../assets/eagle-icons/masks/ic_thumb-up.png": __vite_glob_1_154,
      "../assets/eagle-icons/masks/ic_train.png": __vite_glob_1_155,
      "../assets/eagle-icons/masks/ic_transition.png": __vite_glob_1_156,
      "../assets/eagle-icons/masks/ic_trashbin.png": __vite_glob_1_157,
      "../assets/eagle-icons/masks/ic_tree.png": __vite_glob_1_158,
      "../assets/eagle-icons/masks/ic_truck.png": __vite_glob_1_159,
      "../assets/eagle-icons/masks/ic_tv.png": __vite_glob_1_160,
      "../assets/eagle-icons/masks/ic_twitter.png": __vite_glob_1_161,
      "../assets/eagle-icons/masks/ic_unfield.png": __vite_glob_1_162,
      "../assets/eagle-icons/masks/ic_unlike.png": __vite_glob_1_163,
      "../assets/eagle-icons/masks/ic_untaggeds.png": __vite_glob_1_164,
      "../assets/eagle-icons/masks/ic_upload.png": __vite_glob_1_165,
      "../assets/eagle-icons/masks/ic_video.png": __vite_glob_1_166,
      "../assets/eagle-icons/masks/ic_wallet.png": __vite_glob_1_167,
      "../assets/eagle-icons/masks/ic_watch.png": __vite_glob_1_168,
      "../assets/eagle-icons/masks/ic_water-drop.png": __vite_glob_1_169,
      "../assets/eagle-icons/masks/ic_weapon.png": __vite_glob_1_170,
      "../assets/eagle-icons/masks/ic_website.png": __vite_glob_1_171,
      "../assets/eagle-icons/masks/ic_woman.png": __vite_glob_1_172,
      "../assets/eagle-icons/masks/ic_wrench.png": __vite_glob_1_173
    });
    const manifest = {};
    const register = (relPath, url, kind) => {
      const key = relPath.replace(/\.(svg|png)$/, "");
      if (!manifest[key]) manifest[key] = { url, kind };
      const short = key.split("/").pop();
      if (!manifest[short]) manifest[short] = { url, kind };
    };
    const entries = [
      ...Object.entries(iconUrls).map(
        ([p, u]) => [p.replace("../assets/eagle-icons/icons/", ""), u, "icons"]
      ),
      ...Object.entries(maskUrls).map(
        ([p, u]) => [p.replace("../assets/eagle-icons/masks/", ""), u, "masks"]
      )
    ].sort((a, b) => a[0].split("/").length - b[0].split("/").length);
    for (const [path, url, kind] of entries) register(path, url, kind);
    const MULTI_COLOR = /* @__PURE__ */ new Set([
      "ic-tag-aqua",
      "ic-tag-blue",
      "ic-tag-green",
      "ic-tag-orange",
      "ic-tag-pink",
      "ic-tag-purple",
      "ic-tag-red",
      "ic-tag-yellow",
      "ic-eagle-logo"
    ]);
    const props = __props;
    const attrs = useAttrs();
    const resolved = computed(() => {
      const hit = manifest[props.icon];
      return hit ? { entry: hit, key: props.icon } : null;
    });
    const nativeSize = computed(() => {
      if (!resolved.value) return FALLBACK_SIZE;
      if (resolved.value.entry.kind === "masks") return MASK_BOX;
      return ICON_SIZES[resolved.value.key]?.[0] ?? FALLBACK_SIZE;
    });
    const isMultiColor = computed(() => MULTI_COLOR.has(props.icon));
    const iconStyle = computed(() => {
      const px = props.size !== void 0 ? typeof props.size === "number" ? `${props.size}px` : props.size : `${nativeSize.value}px`;
      const style = {
        width: px,
        height: px,
        flexShrink: "0",
        display: "inline-block",
        verticalAlign: "middle"
      };
      if (!resolved.value || isMultiColor.value) return style;
      const image = `url("${resolved.value.entry.url}")`;
      style.maskImage = image;
      style.maskSize = "contain";
      style.maskRepeat = "no-repeat";
      style.maskPosition = "center";
      style.backgroundColor = props.color;
      return style;
    });
    const mergedClass = computed(() => {
      const classes = ["eagle-icon"];
      if (attrs.class) {
        if (typeof attrs.class === "string") {
          classes.push(attrs.class);
        } else if (Array.isArray(attrs.class)) {
          classes.push(...attrs.class);
        }
      }
      return classes.join(" ");
    });
    return (_ctx, _cache) => {
      return resolved.value && isMultiColor.value ? (openBlock(), createElementBlock("img", {
        key: 0,
        class: normalizeClass(mergedClass.value),
        style: normalizeStyle(iconStyle.value),
        src: resolved.value.entry.url,
        alt: ""
      }, null, 14, _hoisted_1$8)) : (openBlock(), createElementBlock("span", {
        key: 1,
        class: normalizeClass(mergedClass.value),
        style: normalizeStyle(iconStyle.value)
      }, null, 6));
    };
  }
}
